# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )
Rails.application.config.assets.precompile += %w( app/app.js )
Rails.application.config.assets.precompile += %w( app/backgroundbuttonDirective.js )
Rails.application.config.assets.precompile += %w( app/iconController.js )
Rails.application.config.assets.precompile += %w( app/iconDirective.js )
Rails.application.config.assets.precompile += %w( app/iconTableDirective.js )
Rails.application.config.assets.precompile += %w( jscolor.js )
Rails.application.config.assets.precompile += %w( jquery-2.1.3.min.js )
Rails.application.config.assets.precompile += %w( jquery-ui.js )
Rails.application.config.assets.precompile += %w( fabric.js )
Rails.application.config.assets.precompile += %w( fabric.canvasex.js )
Rails.application.config.assets.precompile += %w( jquery.easing.min.js )
Rails.application.config.assets.precompile += %w( jquery.fittext.js )
Rails.application.config.assets.precompile += %w( jquery.magnific-popup.min.js )
Rails.application.config.assets.precompile += %w( scrollreveal.min.js )
Rails.application.config.assets.precompile += %w( homepage.css.scss )
Rails.application.config.assets.precompile += %w( optecturefont.css.scss )
Rails.application.config.assets.precompile += %w( contextmenu_orig.css )
Rails.application.config.assets.precompile += %w( menustyles.css )
Rails.application.config.assets.precompile += %w( canvaswide.js )
Rails.application.config.assets.precompile += %w( circleobject.js )
Rails.application.config.assets.precompile += %w( convenience.js )
Rails.application.config.assets.precompile += %w( customlinearrow.js )
Rails.application.config.assets.precompile += %w( customlinetwoarrow.js )
Rails.application.config.assets.precompile += %w( ellipseobject.js )
Rails.application.config.assets.precompile += %w( imageobject.js )
Rails.application.config.assets.precompile += %w( lineobject.js )
Rails.application.config.assets.precompile += %w( product_configurator.js )
Rails.application.config.assets.precompile += %w( rectobject.js )
Rails.application.config.assets.precompile += %w( textobject.js )
Rails.application.config.assets.precompile += %w( drawing_scripts.js )
Rails.application.config.assets.precompile += %w( menustyles.css )
Rails.application.config.assets.precompile += %w( magnific-popup.css )
Rails.application.config.assets.precompile += %w( spinner.css )
Rails.application.config.assets.precompile += %w( passwordhelper.js )
Rails.application.config.assets.precompile += %w( creative.min.js )
Rails.application.config.assets.precompile += %w( mobile-detect.js )
